---
abstract: ~
author:
  - 'Fabien Wernli, C<< <cpan at faxm0dem.org> >>'
  - 'Fabien Wernli <cpan@faxm0dem.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Collectd::Plugins: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Collectd-Plugins-Compute
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Collectd: 0
  Collectd::Plugins::Common: 0
<<<<<<< HEAD
  Collectd::Unixsock: 0
=======
>>>>>>> a3ed82a5ac4a929fc9f00fda7a5a0476380cb1fa
  Math::RPN: 0
  Try::Tiny: 0
  perl: 5.6.0
  threads: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1001
